version: '3.8'

services:
  nestapp:
    container_name: expense-tracker
    image: personal-expense-tracker
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_TYPE: ${DB_TYPE}
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      PG_PORT: ${PG_PORT}
    depends_on:
      - db
  db:
    container_name: expense-tracker-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
